[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
aoc_driver = "0.3.6"
derive_more = { version = "2", features = ["full"] }
funty = "3.0.0-rc2"
heapless = "0.9"
indoc = { version = "2.0.7", default-features = false }
itertools = { version = "0.14" }
microlp = "0.4.0"
num = "0.4.3"
peg = "0.8"
petgraph = "0.8"
tap = "1.0.1"

[dev-dependencies]
assert2 = "0.4.0"
paste = "1.0.15"
pretty_assertions = "1.4"
rstest = { version = "0.26", default-features = false }

[lib]
name = "aoc_2025"
path = "src/lib.rs"

[features]
default = []
solve = []
analyze = []

[lints.clippy]
tabs_in_doc_comments = "allow"
toplevel_ref_arg = "allow"

[profile.release]
lto = "thin"
codegen-units = 4

[profile.profile]
inherits = "release"
debug = true
